name: Terraform Plan

on:
  push:
    branches:
      - main
      - "feature/**"

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        run: |
          az login --service-principal `
            --username "krishna712@akmalh4921gmail.onmicrosoft.com"
            --password "devopsinsideraug@1234" `
            --tenant "2575fc6b-c79b-46a0-8d6c-12a97e555147"

      - name: Set Azure Subscription
        run: |
          az account set `
            --subscription "YOUR_SUBSCRIPTION_ID"

      - name: Check Azure Login
        run: az account show

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan